import React from 'react'
import KnowMore from './KnowMore'

export default function CollapsedFilters({ emoTitle }) {
  return (
    <>
        <div className='flex flex-row justify-center'>
            <h1 className=' text-2xl'>{emoTitle}</h1>
            <KnowMore>Here will be text generated by gpt for this specific category. Seo optimized. May be pretty long</KnowMore>
        </div>
        <p className=' text-slate-600 text-sm py-2 px-3'>Here will be text generated by gpt for this specific category. Seo optimized.pt for this specific category. Seo optimized. May be pr longHere will be text generated by gpt for this specific category. Seo optimized.c category. Seo optimized. May be pretty longHere will be text generated by gpt for this specific category. Seo optimized May be pretty long</p>
    </>
  )
}
