'use client'
import { useState } from 'react'

import ExpandFiltersButton from './ExpandFiltersButton'
import KnowMore from './KnowMore'
import Link from 'next/link'
import { useSearchParams, useRouter, usePathname } from 'next/navigation'

export default function Filters({ comparisonsList, filters, filtersConfig, selectedFilters, title }) {
  const searchParams = useSearchParams();
  const { replace } = useRouter();
  const pathname = usePathname();
  const filterSelectHandler = (value, fieldName) => () => {
    const params = new URLSearchParams(searchParams);
    params.set(fieldName, value);
    replace(`${pathname}?${params.toString()}`);
  }
  const filterKeys = Object.keys(filters);
  const [isExpanded, setIsExpanded] = useState(false)
  const ExpandedButton = () => <button 
  className='border-x-2 border-t-2 text-sm text-zinc-400 rounded-t-md px-2 mx-10 text-center hover:bg-zinc-100 hover:bg-opacity-50' 
  onClick={() => setIsExpanded(!isExpanded)}>
      {isExpanded ? '▴ Colapse Filters ▴' : '▾ Expand Filters ▾'}
</button>;
  return (isExpanded ? 
    <section
      className={`transition delay-20 duration-500 ease-in-out rounded-b-lg border-2 sticky bg-opacity-10 border-t-white ${
        'jalousie-content bg-stone-200 shadow-lg h-100'
      }`}
    >
        <div className='flex flex-row justify-center'>
            <h1 className=' text-2xl'>{title}</h1>
            <KnowMore>Here will be text generated by gpt for this specific category. Seo optimized. May be pretty long</KnowMore>
        </div>
        <div className='jalousie-content'>
                {comparisonsList.map(({ title, slug }) => <p className='ml-7 jalousie-content-opacity' key={`${slug}_filter`}>
                    <Link href={`/comparison/${slug}`}>
                        {title}
                    </Link>
                </p>)}
            </div>
            {filters[filterKeys[0]].filterValues.map((value) => <p onClick={filterSelectHandler(value, filterKeys[0])}>{value}</p>)}
        <div className='flex flex-col justify-end items-center'>
            <ExpandedButton/>
        </div>
    </section> :
    <section
      className={`transition delay-20 duration-500 ease-in-out rounded-b-lg border-2 sticky bg-opacity-10 border-t-white ${
        ' bg-stone-100 shadow-sm'
      }`}
    >
        <div className='flex flex-row justify-center'>
            <h1 className=' text-2xl'>{title}</h1>
            <KnowMore>Here will be text generated by gpt for this specific category. Seo optimized. May be pretty long</KnowMore>
        </div>
        <div className='flex flex-col justify-end items-center'>
            <ExpandedButton/>
        </div>
    </section>
  )
}
