'use client'
import { useState } from 'react'

import ExpandFiltersButton from './ExpandFiltersButton'
import KnowMore from './KnowMore'

export default function Filters({ filters, selectedFilters, title }) {
  const [isExpanded, setIsExpanded] = useState(false)
  return (
    <section
      className={`transition delay-20 duration-500 ease-in-out rounded-b-lg border-2 sticky bg-opacity-10 border-t-white ${
        isExpanded ? 'jalousie-content bg-stone-200 shadow-lg h-100' : ' bg-stone-100 shadow-sm'
      }`}
    >
        <div className='flex'>
            <h1 className=' text-2xl'>{title}</h1>
            <KnowMore>Here will be text generated by gpt for this specific category. Seo optimized. May be pretty long</KnowMore>
        </div>
        {isExpanded && (
            <div className=''>
                {filters.map((f) => <p className='ml-7 jalousie-content-opacity' key={`${f}_filter`}>{f}</p>)}
            </div>
        )}
        <div className='flex flex-col justify-end items-center'>
            <button 
                className='border-x-2 border-t-2 text-sm text-zinc-400 rounded-t-md px-2 mx-10 text-center hover:bg-zinc-100 hover:bg-opacity-50' 
                onClick={() => setIsExpanded(!isExpanded)}>
                    {isExpanded ? '▴ Colapse Filters ▴' : '▾ Expand Filters ▾'}
            </button>
        </div>
    </section>
  )
}
